### ISSUE TITLE
Some problems.

### ISSUE THREAD

**Issue by ssrlive** [ivmai/tinygc#1]
Hi Ivan, I'm looking for a garbage collector for use in c language, and then I found your tinygc project, I know it is an alternative to [bdwgc](https://github.com/ivmai/bdwgc) , I found tinygc is excellent, both under Linux and macOS and Windows Works well. I want to know that, why did you give up maintaining this project?

Another issue. When I test tinygc under windows with VC2010, the IDE report some memory leak, how to fix it?

My clone is [here](https://github.com/ssrlive/tinygc)

Thanks.

**Comment by ivmai** [comment]
Hello,
Now I'm focused on bdwgc improvement and portability. Let me, in turn, ask you why do you prefer tinygc over bdwgc?

**Comment by ssrlive** [comment]
because it is so small, no dependcy. I like it.

**Comment by ivmai** [comment]
> it is so small

I see. This is not addressed in bdwgc yet.

> no dependency

bdwgc should not have it too.
E.g. you could compile and link it with a single gcc/clang command like "gcc -I include tests/test.c extra/gc.c" - it will produce "a.out" (or "a.exe") which is gctest executable.

**Comment by ssrlive** [comment]
thanks.
